version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth
      - backend
      - db
    networks:
      - app-network

  auth:
    build: ./auth
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./auth:/app
    networks:
      - app-network

  monitoring:
    build:
      context: ./monitoring
    container_name: monitoring
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - db
      - auth
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tourismdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
